### PR TITLE
Fix CppGenerator: handling of fixed/variable list types

### LINKED ISSUE #13: Variable list with primitve types not working (cpp)
How to reproduce:
1. define variable list of type "unsigned byte"
2. define variable list of type "float"
3. run xmlpg
4. try to compile generated class

### LINKED ISSUE #15: cpp: variable length types produce SIGSEGV on unmarshal
Any generated PDU with a `vector` produces a SIGSEGV in `unmarshal` because the vector is never initialized to the required size before data is written into it (array style access).

### PR DESCRIPTION
**Pull request by phoppermann**
fixes #13
fixes #15

### CODE REVIEW

**Comment by leif81** [comment]
@phoppermann thank you for this. I overlooked it until now.

Could you investigate the merge conflict and update the PR with a commit that address the conflict?

**Comment by phoppermann** [comment]
@leif81 I just had a look at the conflicts. Unfortunately, I'm not completely aware of the changes on master in the meantime. Would you mind trying the merge to avoid that I break something?

**Comment by leif81** [comment]
I'm guessing it's related to the auto-indent that happened on 7 July.

https://github.com/open-dis/xmlpg/commit/e78b6b4ab8f04c7404c59643e79ab9ad2d8cc20c

**Comment by leif81** [comment]
I looked into resolving the conflicts but it's not a simple merge conflict. It'd be easier if you closed this PR and re-opened a new one with your changes reapplied to master, one by one by looking at your original commit.

**Comment by phoppermann** [comment]
I have a question regarding this auto-indent: my idea was that I could simply run the auto-indentation on my branch to better see the real differences. However, I do not quite understand currently how this auto-indentation is/has been done. I was expecting something like `formatter-maven-plugin`.

**Comment by leif81** [comment]
I did it with Netbeans using the default formatting settings for Java.

I wasn't aware of the formatter plugin, I'll try that in the future.

**Comment by phoppermann** [comment]
See #23.

**Comment by phoppermann** [comment]
The merge is finished. It should be fine but nevertheless you should have a detailed look at it and try it out because the merge wasn't quite straight forward as you know.

General remark: I suggest to squash the commits when merging such that you do not get all tiny commits from the branches in master.

**Comment by leif81** [comment]
Thank-you @phoppermann

**Pull request merged**
